---

  hermes_base_url:
    description: "Please fill in"
    type: "string"
    required: false

  hermes_user:
    description: "Please fill in"
    type: "string"
    required: false

  hermes_token:
    description: "Please fill in"
    type: "string"
    required: false



  summary_host:
    description: "Please fill in"
    type: "string"
    required: false

  summary_user:
    description: "Please fill in"
    type: "string"
    required: false

  summary_host_key:
    description: "Please fill in"
    type: "string"
    required: false

  summary_destination:
    description: "Please fill in"
    type: "string"
    required: false

  summary_ngi_pipeline_reports_destination:
    description: "Please fill in"
    type: "string"
    required: false



  biotank_hosts:
    description: "Please fill in"
    type: "string"
    required: false

  biotank_user:
    description: "Please fill in"
    type: "string"
    required: false

  biotank_user_key:
    description: "Please fill in"
    type: "string"
    required: false

  check_cert_slack_channel:
    description: "Please fill in"
    type: "string"
    required: false



  remote_host:
    description: "Please fill in"
    type: "string"
    required: false

  remote_user:
    description: "Please fill in"
    type: "string"
    required: false

  remote_host_key:
    description: "Please fill in"
    type: "string"
    required: false

  remote_destination:
    description: "Please fill in"
    type: "string"
    required: false

  remote_sisyphus_location:
    description: "Please fill in"
    type: "string"
    required: false



  ngi_pipeline_url:
    description: "Please fill in"
    type: "string"
    required: false



  irma_api_key:
    description: "Please fill in"
    type: "string"
    required: false

  irma_remote_path:
    description: "Please fill in"
    type: "string"
    required: false

  irma_reports_remote_path:
    description: "Please fill in"
    type: "string"
    required: false

  irma_checksum_base_url:
    description: "Please fill in"
    type: "string"
    required: false

  irma_siswrap_base_url:
    description: "Please fill in"
    type: "string"
    required: false



  delivery_service_url:
    description: "Please fill in"
    type: "string"
    required: false



  irma_replace_expressions:
    description: "Please fill in"
    type: "array"
    items:
      type: "string"
    required: false



  send_mail_to:
    description: "Please fill in"
    type: "string"
    required: false



  runfolder_service_port:
    description: "Please fill in"
    type: "integer"
    required: false

  bcl2fastq_service_port:
    description: "Please fill in"
    type: "integer"
    required: false

  siswrap_service_port:
    description: "Please fill in"
    type: "integer"
    required: false



  runfolder_svc_urls:
    description: "The service URL polled in the runfolder sensor"
    type: "array"
    items:
      type: "string"
    required: false



  incoming_svc_urls:
    description: "Please fill in"
    type: "array"
    items:
      type: "object"
      additionalProperties: false
      required: true
      properties:
        url:
          description: "Please fill in"
          type: "string"
          required: true
        dest_folder:
          description: "Please fill in"
          type: "string"
          required: true
        remote_user:
          description: "Please fill in"
          type: "string"
          required: true
        user_key:
          description: "Please fill in"
          type: "string"
          required: true
    required: false



  charon_api_token:
    description: "Please fill in"
    type: "string"
    required: false

  charon_base_url:
    description: "Please fill in"
    type: "string"
    required: false

  slack_webhook_url:
    description: "Please fill in"
    type: "string"
    required: false

  charon_status_report_slack_channel:
    description: "Please fill in"
    type: "string"
    required: false



  delivery_workflow_status_slack_channel:
    description: "Please fill in"
    type: "string"
    required: false

  archive_excludes:
    description: "String of file paths to exclude from the compressed archive (egrep syntax)"
    type: "string"
    required: false

  archive_exclude_links:
    description: "Which file entries we should not link to when creating the archive copy of the runfolder"
    type: "string"
    required: false

  archive_fastq_threshold:
    description: "Minimum number of fastq files to expect when creating archive. If we find less files than this then the action will fail"
    type: "string"
    required: false

  archive_python_path:
    description: "Please fill in"
    type: "string"
    required: false



  supr_api_user:
    description: "Please fill in"
    type: "string"
    required: false

  supr_api_key:
    description: "Please fill in"
    type: "string"
    required: false

  supr_api_url:
    description: "Please fill in"
    type: "string"
    required: false
