---

runfolder_service_url:
  description: "Urls for the runfolder service"
  type: "array"
  items:
    type: "string"
  required: false

bcl2fastq_service_url:
  description: "Url for the bcl2fastq service"
  type: "string"
  required: false
  default: http://bcl2fastq-service

checkqc_service_url:
  description: "Url for the bcl2fastq service"
  type: "string"
  required: false
  default: http://checkqc-service
