---

runfolder_service_url:
  description: "Urls for the runfolder service"
  type: "string"
  required: false
  default: http://runfolder-service/api/1.0/runfolders/pickup

bcl2fastq_service_url:
  description: "Url for the bcl2fastq service"
  type: "string"
  required: false
  default: http://bcl2fastq-service

checkqc_service_url:
  description: "Url for the bcl2fastq service"
  type: "string"
  required: false
  default: http://checkqc-service
