#!/bin/bash
set -e

if [ "$(whoami)" != "stanley" ] && [ "$(whoami)" != "root" ]; then 
  echo "This script should be run with the stanley account or as root" 1>&2
  exit 1
fi 

# Ensure that we have the folders to be followed:o

monitored_base=/home/stanley/arteria/tests/monitored

for i in {1..2}
do 
  monitored=$monitored_base/mon$i
  echo "Creating $monitored"
  mkdir -p $monitored
  chown stanley:stanley $monitored
done

# For now, we just create everything in the first mon folder:
basefolder=$monitored_base/mon1
runfolder="$basefolder/runfolder_$(date +%s)"
echo "Creating $runfolder"
mkdir -p $runfolder

if [ "$1" == "" ]
then
  sleep_for=0
else
  sleep_for=$1
fi

echo Sleeping for $sleep_for seconds

sleep $sleep_for

complete_file="$runfolder/RTAComplete.txt"
echo "Adding the file RTAComplete.txt to $runfolder, indicating successful processing on seq device"
touch $complete_file

echo "DONE"
