#!/usr/bin/env bash
# Licensed to the StackStorm, Inc ('StackStorm') under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Script which tries to register all the resources from a particular pack and
# fails (exits with non-zero) if registering a particular resource fails.
#

if hash greadlink 2>/dev/null; then
    SCRIPT_PATH=$(dirname "$(greadlink -f "$0")")
else
    SCRIPT_PATH=$(dirname "$(readlink -f "$0")")
fi


CONFIG_FILE=${1:-/st2.tests.conf}

source ${SCRIPT_PATH}/common.sh

PACK_PATH=$PWD
PACK_NAME=$(basename ${PACK_PATH})

ST2_REPO_PATH="st2/"
ST2_COMPONENTS=$(get_st2_components)
PACK_PYTHONPATH=$(join ":" ${ST2_COMPONENTS})

REGISTER_SCRIPT_PATH="${ST2_REPO_PATH}/st2common/bin/st2-register-content"
# Note: -v verbose flag has been removed to work around Travis log size limits
REGISTER_SCRIPT_COMMON_FLAGS="--register-fail-on-failure --config-file=${CONFIG_FILE}"

REGISTER_SCRIPT_REGISTER_FLAGS="--register-all"

source venv/bin/activate

# Set PYTHONPATH to include st2 components
export PYTHONPATH=${PACK_PYTHONPATH}:${PYTHONPATH}

echo "Registering content from pack ${PACK_NAME}"
${REGISTER_SCRIPT_PATH} ${REGISTER_SCRIPT_COMMON_FLAGS} ${REGISTER_SCRIPT_REGISTER_FLAGS} --register-pack=${PACK_PATH}
EXIT_CODE=$?

if [ ${EXIT_CODE} -ne 0 ]; then
    echo "Registering resources for pack ${PACK_NAME} failed"
fi

exit ${EXIT_CODE}
