---
name: "arteria-packs.check_irma_certs"
pack: "arteria-packs"
description: "Warn if Irma certs expire soon"
enabled: true

trigger:
    type: "core.st2.CronTimer"
    parameters:
      timezone: "UTC"
      hour: 07
      minute: 30
      second: 0

action:
    ref: "arteria-packs.check_irma_certs"

