---
name: "arteria-packs.fill_projman"
pack: "arteria-packs"
description: "Attempts to fill the ProjMan database at the set intervals."
enabled: true

trigger:
    type: "core.st2.IntervalTimer"
    parameters:
      unit: hours
      delta: 2

action:
    ref: "arteria-packs.fill_projman"


