---
name: "arteria.fill_projman"
pack: "arteria"
description: "Attempts to fill the ProjMan database at the set intervals."
enabled: false

trigger:
    type: "core.st2.IntervalTimer"
    parameters:
      unit: hours
      delta: 2

action:
    ref: "arteria.fill_projman"


