---

name: "arteria.mv_runfolders_from_incoming_to_processing"
pack: "arteria"
description: "Checks the incoming runfolders service for runfolders that have been uploaded completely and moves them to the processing folder"
enabled: true

trigger:
    type: "arteria.incoming_ready"

action:
    ref: "linux.mv"
    parameters:
        hosts: "{{ trigger.host }}"
        source: "{{ trigger.runfolder }}"
        destination: "{{ trigger.destination }}"
        username: "{{ trigger.remote_user }}"
        private_key: "{{ trigger.user_key }}"
