---
name: "arteria.when_runfolder_is_ready_run_ngi_pipeline"
description: "Fires of the NGI pipeline when a runfolder is ready"
enabled: true

trigger:
    type: "arteria.runfolder_ready"

action:
    ref: "arteria.ngi_uu_workflow"
    parameters:
        host: "{{trigger.host}}"
        runfolder: "{{trigger.runfolder}}"


